package org.xibo.playerhost.player

enum class PlayerState {
    UNCONFIGURED, CONNECTING, REGISTERING, WAITING_FOR_AUTHORIZATION,
    SYNCING, DOWNLOADING, READY, PLAYING, OFFLINE_PLAYING,
    ERROR_RECOVERABLE, ERROR_FATAL
}
